[package]
authors = ["Valeriy Kostikov <mkoctuk@gmail.com>"]
edition = "2018"
name = "netc"
version = "0.5.1"

[dependencies]
base64 = "0.13"
bytes = "1.0"
rsl = {version = "0.4", git = "https://github.com/serbe/rsl"}
thiserror = "1.0"
tokio = {version = "1.3", features = ["net", "io-util"]}
tokio-rustls = "0.22"
uri = {version = "0.3", git = "https://github.com/serbe/uri"}
webpki-roots = "0.21"

[dev-dependencies]
dotenv = "0.15"
lazy_static = "1.4"
tokio = {version = "1.1", features = ["full"]}
